version: '2'

services:
  confluence:
    image: eugenmayer/confluence:${CONFLUENCE_VERSION}
    build:
      context: ./
      args:
        CONFLUENCE_VERSION: ${CONFLUENCE_VERSION}
    container_name: confluence
    volumes:
      - confluencedata:/var/atlassian/confluence
    links:
      - mysql:db
    ports:
      - '80:8090'
      - '8091:8091'
    environment:
      - CONFLUENCE_DB_HOST=db
      - CONFLUENCE_DB_PORT=5432
      - CATALINA_OPTS=-Xms256m -Xmx1g
      - CONFLUENCE_PROXY_NAME=
      - CONFLUENCE_PROXY_PORT=
      - CONFLUENCE_PROXY_SCHEME=
      - CONFLUENCE_DELAYED_START=
      # those are preconfigurations so that we do not need to set our DB creds when installing - you can also
      # no use that and do it manually during the interactive installation
      # TODO: eventhough it lands in the configuration it seems to not really picked up by confluence during the installation
      - CONFLUENCE_CONFIG_PROPERTY1=hibernate.connection.driver_class
      - CONFLUENCE_CONFIG_VALUE1=org.mysql.Driver
      # - CONFLUENCE_CONFIG_VALUE1=org.postgresql.Driver
      - CONFLUENCE_CONFIG_PROPERTY2=hibernate.connection.password
      - CONFLUENCE_CONFIG_VALUE2=jellyfish
      - CONFLUENCE_CONFIG_PROPERTY3=hibernate.connection.url
      # - CONFLUENCE_CONFIG_VALUE3=jdbc:postgresql://db:5432/confluencedb
      - CONFLUENCE_CONFIG_VALUE3=mysql://confluencedb@mysql/confluencedb
      - CONFLUENCE_CONFIG_PROPERTY4=hibernate.connection.username
      - CONFLUENCE_CONFIG_VALUE4=confluencedb
      #- CONFLUENCE_CONFIG_PROPERTY1=confluence.setup.server.id
      #- CONFLUENCE_CONFIG_VALUE1=BDYQ-V8CF-XUYW-DIWK
#  postgresql:
#    image: blacklabelops/postgres
#    container_name: postgres
#    volumes:
#      - postgresqldata:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=confluencedb
#      - POSTGRES_PASSWORD=jellyfish
#      - POSTGRES_DB=confluencedb
#      - POSTGRES_ENCODING=UTF8
#      - POSTGRES_COLLATE=C
#      - POSTGRES_COLLATE_TYPE=C
  mysql:
    image: mysql:5.6
    environment:
      - 'MYSQL_ROOT_PASSWORD=verybigsecretrootpassword'
      - 'MYSQL_DATABASE=confluencedb'
      - 'MYSQL_USER=confluencedb'
      - 'MYSQL_PASSWORD=jellyfish'
volumes:
  confluencedata:
    external: false
  postgresqldata:
    external: false
